#!/usr/bin/env bash
#displaying content of files
while IFS=: read -r user pass uid gid desc home shell
do
    echo "Username: $user"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
