#!/usr/bin/env bash
#writing script that loops from 1 to 10
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "Bad luck"
	elif " [ $i -eq 8 ]
	then
		echo "Good luck"
	else 
		echo "best School"
	fi

	i=$((i+1))
done
