#!/usr/bin/env bash
#display the time for 12 hours and 59 minutes

hour=00

while [ $hour -le 12 ]
do echo $hour
    minute=00
    while [ $minute -le 59 ]
    do
        echo "$hour:$minute"
        minute=$((minute+1))
    done
    hour=$((hour+1))
done
