#!/usr/bin/env bash
#infromation about school files

FILE="school"

if [ -f "$FILE" ]; then
    echo "school file exists"
    if [ -s "$FILE" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -r "$FILE" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi

