#!/usr/bin/env bash
#displaying process
# Function to display process hierarchy recursively
display_processes() {
  local pid=$1
  local level=$2

  # Get information about the process
  local p_info=$(ps -o pid,ppid,user,command --no-headers -p $pid)
  local p_pid=$(echo $p_info | awk '{print $2}')
  local p_user=$(echo $p_info | awk '{print $3}')
  local p_command=$(echo $p_info | awk '{print $4}')

  # Indent the process command based on the process hierarchy level
  local indentation=""
  for ((i=1; i<$level; i++)); do
    indentation+="  "
  done

  # Print the process information
  printf "%-6s%-6s%-10s%s%s\n" "$pid" "$p_pid" "$p_user" "$indentation" "$p_command"

  # Recursively display child processes
  local child_pids=$(pgrep -P $pid)
  for child_pid in $child_pids; do
    display_processes $child_pid $((level+1))
  done
}

echo "PID    PPID   USER      COMMAND"
echo "--------------------------------"

# Get the list of all processes
all_pids=$(ps -e -o pid=)

# Iterate over each process
for pid in $all_pids; do
  display_processes $pid 0
done
